from django.db import models


class ErrorCode(models.TextChoices):
    # Auth / Accounts
    USER_ALREADY_EXISTS   = "USER_ALREADY_EXISTS"
    INVALID_CREDENTIALS   = "INVALID_CREDENTIALS"
    ACCOUNT_DISABLED      = "ACCOUNT_DISABLED"
    REGISTER_FAILED       = "REGISTER_FAILED"
    PROFILE_UPDATE_FAILED = "PROFILE_UPDATE_FAILED"

    # Company
    COMPANY_ALREADY_EXISTS = "COMPANY_ALREADY_EXISTS"
    COMPANY_CREATE_FAILED  = "COMPANY_CREATE_FAILED"
    COMPANY_UPDATE_FAILED  = "COMPANY_UPDATE_FAILED"
    COMPANY_DELETE_FAILED  = "COMPANY_DELETE_FAILED"
    COMPANY_NOT_FOUND      = "COMPANY_NOT_FOUND"

    # Job
    JOB_CREATE_FAILED = "JOB_CREATE_FAILED"
    JOB_UPDATE_FAILED = "JOB_UPDATE_FAILED"
    JOB_DELETE_FAILED = "JOB_DELETE_FAILED"
    JOB_NOT_FOUND     = "JOB_NOT_FOUND"

    # Generic
    VALIDATION_ERROR  = "VALIDATION_ERROR"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_FOUND         = "NOT_FOUND"
    SERVER_ERROR      = "SERVER_ERROR"
    UNKNOWN_ERROR     = "UNKNOWN_ERROR"
